
await figma.loadFontAsync({ family: "Noto Sans KR", style: "Medium" });
await figma.loadFontAsync({ family: "Noto Sans KR", style: "Bold" });
await figma.loadFontAsync({ family: "Noto Sans KR", style: "Regular" });
const frame = figma.getNodeById("FRAME_ID");
const created = [];

  const t0 = figma.createText();
  frame.appendChild(t0);
  t0.characters = `실제 사례`;
  t0.fontSize = 22;
  t0.fills = [{ type: "SOLID", color: { r: 1.0, g: 1.0, b: 1.0 } }];
  t0.fontName = { family: "Noto Sans KR", style: "Bold" };
  t0.textAlignHorizontal = "CENTER";
  t0.resize(300, 56);
  t0.x = 390; t0.y = 80;
  created.push(t0.id);
  const t1 = figma.createText();
  frame.appendChild(t1);
  t1.characters = `48세 직장인`;
  t1.fontSize = 28;
  t1.fills = [{ type: "SOLID", color: { r: 0.969, g: 0.973, b: 0.98 } }];
  t1.fontName = { family: "Noto Sans KR", style: "Medium" };
  t1.textAlignHorizontal = "CENTER";
  t1.resize(900, 60);
  t1.x = 90; t1.y = 220;
  created.push(t1.id);
  const t2 = figma.createText();
  frame.appendChild(t2);
  t2.characters = `건강검진 황색등 2년 방치 후 수술`;
  t2.fontSize = 26;
  t2.fills = [{ type: "SOLID", color: { r: 0.969, g: 0.973, b: 0.98 } }];
  t2.fontName = { family: "Noto Sans KR", style: "Regular" };
  t2.textAlignHorizontal = "CENTER";
  t2.resize(900, 60);
  t2.x = 90; t2.y = 300;
  created.push(t2.id);
  const t3 = figma.createText();
  frame.appendChild(t3);
  t3.characters = `2,800만원`;
  t3.fontSize = 140;
  t3.fills = [{ type: "SOLID", color: { r: 1.0, g: 1.0, b: 1.0 } }];
  t3.fontName = { family: "Noto Sans KR", style: "Bold" };
  t3.textAlignHorizontal = "CENTER";
  t3.resize(900, 200);
  t3.x = 90; t3.y = 420;
  created.push(t3.id);
  const t4 = figma.createText();
  frame.appendChild(t4);
  t4.characters = `보험 공백으로 전액 자기부담`;
  t4.fontSize = 28;
  t4.fills = [{ type: "SOLID", color: { r: 0.969, g: 0.973, b: 0.98 } }];
  t4.fontName = { family: "Noto Sans KR", style: "Regular" };
  t4.textAlignHorizontal = "CENTER";
  t4.resize(900, 60);
  t4.x = 90; t4.y = 640;
  created.push(t4.id);
  const t5 = figma.createText();
  frame.appendChild(t5);
  t5.characters = `실제 고객 사례 (익명 처리)`;
  t5.fontSize = 18;
  t5.fills = [{ type: "SOLID", color: { r: 0.6, g: 0.6, b: 0.6 } }];
  t5.fontName = { family: "Noto Sans KR", style: "Regular" };
  t5.textAlignHorizontal = "CENTER";
  t5.resize(600, 50);
  t5.x = 90; t5.y = 990;
  created.push(t5.id);
  const t6 = figma.createText();
  frame.appendChild(t6);
  t6.characters = `보험 증권 진단가`;
  t6.fontSize = 18;
  t6.fills = [{ type: "SOLID", color: { r: 0.878, g: 0.486, b: 0.227 } }];
  t6.fontName = { family: "Noto Sans KR", style: "Medium" };
  t6.textAlignHorizontal = "CENTER";
  t6.resize(220, 50);
  t6.x = 820; t6.y = 990;
  created.push(t6.id);
return { createdNodeIds: created };
