
await figma.loadFontAsync({ family: "Noto Sans KR", style: "Medium" });
await figma.loadFontAsync({ family: "Noto Sans KR", style: "Regular" });
await figma.loadFontAsync({ family: "Noto Sans KR", style: "Bold" });
const frame = figma.getNodeById("FRAME_ID");
const created = [];

  const t0 = figma.createText();
  frame.appendChild(t0);
  t0.characters = `지금 당신의 수치는
아직 '경고'일 뿐입니다`;
  t0.fontSize = 44;
  t0.fills = [{ type: "SOLID", color: { r: 1.0, g: 1.0, b: 1.0 } }];
  t0.fontName = { family: "Noto Sans KR", style: "Bold" };
  t0.textAlignHorizontal = "CENTER";
  t0.resize(900, 180);
  t0.x = 90; t0.y = 160;
  created.push(t0.id);
  const t1 = figma.createText();
  frame.appendChild(t1);
  t1.characters = `보험과 연결되지 않으면 경고로 끝나지 않습니다`;
  t1.fontSize = 22;
  t1.fills = [{ type: "SOLID", color: { r: 0.969, g: 0.973, b: 0.98 } }];
  t1.fontName = { family: "Noto Sans KR", style: "Regular" };
  t1.textAlignHorizontal = "CENTER";
  t1.resize(900, 60);
  t1.x = 90; t1.y = 370;
  created.push(t1.id);
  const t2 = figma.createText();
  frame.appendChild(t2);
  t2.characters = `카톡으로 증권 사진 한 장
→ 무료 1차 진단`;
  t2.fontSize = 32;
  t2.fills = [{ type: "SOLID", color: { r: 1.0, g: 1.0, b: 1.0 } }];
  t2.fontName = { family: "Noto Sans KR", style: "Bold" };
  t2.textAlignHorizontal = "CENTER";
  t2.resize(700, 160);
  t2.x = 190; t2.y = 520;
  created.push(t2.id);
  const t3 = figma.createText();
  frame.appendChild(t3);
  t3.characters = `카카오채널 아이디를 여기에 입력하세요`;
  t3.fontSize = 20;
  t3.fills = [{ type: "SOLID", color: { r: 0.969, g: 0.973, b: 0.98 } }];
  t3.fontName = { family: "Noto Sans KR", style: "Regular" };
  t3.textAlignHorizontal = "CENTER";
  t3.resize(900, 50);
  t3.x = 90; t3.y = 800;
  created.push(t3.id);
  const t4 = figma.createText();
  frame.appendChild(t4);
  t4.characters = `보험 증권 진단가`;
  t4.fontSize = 18;
  t4.fills = [{ type: "SOLID", color: { r: 0.878, g: 0.486, b: 0.227 } }];
  t4.fontName = { family: "Noto Sans KR", style: "Medium" };
  t4.textAlignHorizontal = "CENTER";
  t4.resize(220, 50);
  t4.x = 820; t4.y = 990;
  created.push(t4.id);
return { createdNodeIds: created };
