
await figma.loadFontAsync({ family: "Noto Sans KR", style: "Bold" });
const frame = figma.getNodeById("FRAME_ID");
const created = [];

  const t0 = figma.createText();
  frame.appendChild(t0);
  t0.characters = `경고 수치를 방치하면 생기는 일`;
  t0.fontSize = 32;
  t0.fills = [{ type: "SOLID", color: { r: 0.102, g: 0.184, b: 0.369 } }];
  t0.fontName = { family: "Noto Sans KR", style: "Bold" };
  t0.textAlignHorizontal = "CENTER";
  t0.resize(900, 70);
  t0.x = 90; t0.y = 80;
  created.push(t0.id);
  const t1 = figma.createText();
  frame.appendChild(t1);
  t1.characters = `검진 결과 무시`;
  t1.fontSize = 22;
  t1.fills = [{ type: "SOLID", color: { r: 1.0, g: 1.0, b: 1.0 } }];
  t1.fontName = { family: "Noto Sans KR", style: "Bold" };
  t1.textAlignHorizontal = "CENTER";
  t1.resize(240, 60);
  t1.x = 90; t1.y = 350;
  created.push(t1.id);
  const t2 = figma.createText();
  frame.appendChild(t2);
  t2.characters = `질병 악화`;
  t2.fontSize = 22;
  t2.fills = [{ type: "SOLID", color: { r: 1.0, g: 1.0, b: 1.0 } }];
  t2.fontName = { family: "Noto Sans KR", style: "Bold" };
  t2.textAlignHorizontal = "CENTER";
  t2.resize(240, 60);
  t2.x = 420; t2.y = 350;
  created.push(t2.id);
  const t3 = figma.createText();
  frame.appendChild(t3);
  t3.characters = `의료비 폭증`;
  t3.fontSize = 22;
  t3.fills = [{ type: "SOLID", color: { r: 1.0, g: 1.0, b: 1.0 } }];
  t3.fontName = { family: "Noto Sans KR", style: "Bold" };
  t3.textAlignHorizontal = "CENTER";
  t3.resize(240, 60);
  t3.x = 750; t3.y = 350;
  created.push(t3.id);
  const t4 = figma.createText();
  frame.appendChild(t4);
  t4.characters = `보험 보장이 없으면, 이 의료비 전부 본인 부담`;
  t4.fontSize = 24;
  t4.fills = [{ type: "SOLID", color: { r: 1.0, g: 1.0, b: 1.0 } }];
  t4.fontName = { family: "Noto Sans KR", style: "Bold" };
  t4.textAlignHorizontal = "CENTER";
  t4.resize(900, 70);
  t4.x = 90; t4.y = 860;
  created.push(t4.id);
return { createdNodeIds: created };
